# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Cadastro(object):
    def setupUi(self, Form_Cadastro):
        Form_Cadastro.setObjectName("Form_Cadastro")
        Form_Cadastro.resize(687, 566)
        self.centralwidget = QtWidgets.QWidget(Form_Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 50, 531, 381))
        self.widget.setStyleSheet("background-color: rgb(29, 92, 132);\n"
"border-radius:20px;")
        self.widget.setObjectName("widget")
        self.cadastro_password = QtWidgets.QLineEdit(self.widget)
        self.cadastro_password.setGeometry(QtCore.QRect(140, 150, 311, 20))
        self.cadastro_password.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 155, 255);\n"
"padding-bottom:7px")
        self.cadastro_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cadastro_password.setObjectName("cadastro_password")
        self.cadastro_usuario = QtWidgets.QLineEdit(self.widget)
        self.cadastro_usuario.setGeometry(QtCore.QRect(140, 110, 311, 20))
        self.cadastro_usuario.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 155, 255);\n"
"padding-bottom:7px")
        self.cadastro_usuario.setObjectName("cadastro_usuario")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 120, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: 0")
        self.label.setObjectName("label")
        self.msg_label = QtWidgets.QLabel(self.widget)
        self.msg_label.setGeometry(QtCore.QRect(120, 290, 281, 16))
        self.msg_label.setText("")
        self.msg_label.setObjectName("msg_label")
        self.cadastrarButton = QtWidgets.QPushButton(self.widget)
        self.cadastrarButton.setGeometry(QtCore.QRect(210, 270, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cadastrarButton.setFont(font)
        self.cadastrarButton.setStyleSheet("\n"
"QPushButton#cadastrarButton{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#cadastrarButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(66, 199, 255, 100), stop:1 rgba(255, 255, 255, 100));\n"
"}\n"
"\n"
"QPushButton#cadastrarButton{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"}\n"
"")
        self.cadastrarButton.setObjectName("cadastrarButton")
        self.repeat_password = QtWidgets.QLineEdit(self.widget)
        self.repeat_password.setGeometry(QtCore.QRect(140, 190, 311, 20))
        self.repeat_password.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"border: 1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 255);\n"
"color:rgb(255, 155, 255);\n"
"padding-bottom:7px")
        self.repeat_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeat_password.setObjectName("repeat_password")
        self.msg_label2 = QtWidgets.QLabel(self.widget)
        self.msg_label2.setGeometry(QtCore.QRect(140, 220, 311, 21))
        self.msg_label2.setText("")
        self.msg_label2.setObjectName("msg_label2")
        Form_Cadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_Cadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 21))
        self.menubar.setObjectName("menubar")
        Form_Cadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_Cadastro)
        self.statusbar.setObjectName("statusbar")
        Form_Cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(Form_Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Form_Cadastro)

    def retranslateUi(self, Form_Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Form_Cadastro.setWindowTitle(_translate("Form_Cadastro", "MainWindow"))
        self.cadastro_password.setPlaceholderText(_translate("Form_Cadastro", "Digite a senha"))
        self.cadastro_usuario.setPlaceholderText(_translate("Form_Cadastro", "Usuario"))
        self.label.setText(_translate("Form_Cadastro", ""))
        self.cadastrarButton.setText(_translate("Form_Cadastro", "Cadastrar"))
        self.repeat_password.setPlaceholderText(_translate("Form_Cadastro", "Repita a senha"))
